### ISSUE TITLE
🗞 Add Setup section to README.md file

### ISSUE THREAD

**Issue by PrerakMathur20** [iiitl/geet-hub-community#1]
📄 Add Setup section to README.md file
---

To allow easy setup of the project, create a **Setup** section in the `README.md` file and add steps on how locally allow the setup of the project.

The _Setup_ Section must include the following -

* Create a Fork
* `git clone` the project
* Check for Prerequisites for the project
* Commands for Initiating and running the project

**Comment by AjayMaheshwari23** [comment]
can I add the setup section in Readme ?

**Comment by PrerakMathur20** [comment]
@AjayMaheshwari23 
To give a fair opportunity to everyone, issues are assigned on one after one basis. As since, you've already been assigned another issue, kindly complete that one, to get another issue assigned.

**Comment by 1-Sanchit-1** [comment]
I would like to work on this issue!

**Comment by deep-69bits** [comment]
Can i work on it??

**Comment by PrerakMathur20** [comment]
@1-Sanchit-1 Assigned to you!

@deep-69bits Since the issues are FCFS, this issue, can't be assigned to you. Feel free to look around other issues you are comfortable with.
