### ISSUE TITLE
🗄 Connect a Database

### ISSUE THREAD

**Issue by PrerakMathur20** [iiitl/geet-hub-community#2]
🗄 Connect a Database
---

Using Mongo atlas database, connect a database for the project to store the data and audio file details on a server, instead of storing them locally.

**NOTE**
Once assigned, ask the maintainer for the mongo credentials to connect to the database, _DO NOT USE PERSONAL MONGO STORAGE_.

**Comment by palashb01** [comment]
Please assign it to me and Please provide the Schema for the database.

**Comment by PrerakMathur20** [comment]
@palashb01 
Assigned to you!
The database design and schema are left up for you to pick up. You can refer to the existing code to design the schema yourself. Feel free to ask any other doubts here.

**Comment by PrerakMathur20** [comment]
@palashb01 Any Updates?

**Comment by palashb01** [comment]
@PrerakMathur20 I have resolved this Issue, will PR tomorrow.
