### ISSUE TITLE
⚡️Add dark mode

### ISSUE THREAD

**Issue by PrerakMathur20** [iiitl/geet-hub-community#4]
⚡️Add dark mode
---
Add a dark mode toggle switch in the navbar for users to toggle between the _Light_ and _Dark_ modes of the website.
Use BootStrap or MaterialUI to implement the same.

Refer - 
* [BootStrap](https://react-bootstrap.netlify.app/components/navbar/#color-schemes)
* [MaterialUI](https://mui.com/material-ui/customization/dark-mode/#dark-mode-by-default)

**Comment by AjayMaheshwari23** [comment]
Can I contribute on this issue .

**Comment by AjayMaheshwari23** [comment]
https://user-images.githubusercontent.com/96301800/193425626-6dc2ba21-9edb-41ab-ae83-0772ac52518d.mov

Sir is it okay ?

**Comment by AjayMaheshwari23** [comment]
I have changed that "Toggle mode" text  to switch between "Light Mode" and "Dark Mode" as we click on it .

**Comment by PrerakMathur20** [comment]
Kindly Create a PR and link the issue to allow us to check your code better.
